apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dedm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dedm
    app.kubernetes.io/part-of: ci1t-830-0041-app
  name: devfile-sample-dedm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dedm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dedm
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0041-tenant/ci1t-830-0041-app/devfile-sample-dedm@sha256:3bd8a209c0edb2a6a873455fa5edcefcc952f6a3ad15b56bd0cb290bee31ec38
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
